### ISSUE TITLE
[BUG]: wandb failure: CommError (HTTP 403)

### ISSUE THREAD

**Issue by cool-RR** [ucl-dark/pax#174]
### Description

I run this: 

```
python -m pax.experiment +experiment/ipd=mfos_att_v_tabular ++runner="evo" ++env_type="meta" ++wandb.log=True ++wandb.project=my-awesome-project
```

And I get this: 

```
[...]
File "/home/ramrachum/.venvs/jax_env/lib/python3.11/site-packages/wandb/sdk/internal/internal_api.py", line 338, in gql
  ret = self._retry_gql(
File "/home/ramrachum/.venvs/jax_env/lib/python3.11/site-packages/wandb/sdk/lib/retry.py", line 147, in __call__
  retry_timedelta_triggered = check_retry_fn(e)
File "/home/ramrachum/.venvs/jax_env/lib/python3.11/site-packages/wandb/util.py", line 965, in check_retry_fn
  return fallback_retry_fn(e)
File "/home/ramrachum/.venvs/jax_env/lib/python3.11/site-packages/wandb/util.py", line 907, in no_retry_auth
  raise CommError(

wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 403: Forbidden)
```

And when I comment out these lines:

```
def global_setup(args):
    """Set up global variables."""
    save_dir = f"{args.save_dir}/{str(datetime.now()).replace(' ', '_').replace(':', '.')}"
    if not args.runner == "eval":
        os.makedirs(
            save_dir,
            exist_ok=True,
        )
    if args.wandb.log:
        print("run name", str(args.wandb.name))
        if args.debug:
            args.wandb.group = "debug-" + args.wandb.group
        run = wandb.init(
            # reinit=True,
            # entity=str(args.wandb.entity),
            project=str(args.wandb.project),
            # group=str(args.wandb.group),
            # name=str(args.wandb.name),
            # mode=str(args.wandb.mode),
            # tags=args.wandb.tags,
            config=omegaconf.OmegaConf.to_container(
                args, resolve=True, throw_on_missing=True
            ),  # type: ignore
            # settings=wandb.Settings(code_dir="."),
        )
        print("run id", run.id)
        wandb.run.log_code(".")
    return save_dir
```

Suddenly it works.

### What pax version are you using?

4a27eb7874863e5e485d8db6cb6569b6c515c5ad

### What jax/jaxlib version are you using?

0.4.20

### Which accelerator(s) are you using?

CPU

### Additional system info

Python 3.11 on Ubuntu

**Comment by Aidandos** [comment]
Hi Ram, you need to change the wandb args in the yaml file if you have wandb.log=True. I added a reminder to the README.

**Comment by cool-RR** [comment]
I understand. It should be noted that it's not ideal that users have to change the code that ships with the program in order to use it in the most basic way.

**Comment by Aidandos** [comment]
You're not changing the code, that's just the wandb login credentials. If you set wandb.log=True, that means you want to log over wandb, which means you need an account. It's actually reassuring that it doesn't run if you don't change your wandb credentials. 
You can choose to not use wandb by setting wandb.log=False and can use your own logging system. Some local logging is even already provided within pax.
However, I believe what you are looking for is a more in-depth, step by step tutorial to create an experiment within pax, including setting up a wandb experiment. I'll write something up when I find the time. Nonetheless, I don't think setting up wandb should be a huge hurdle to start writing experiments. There are also a lot of resources on the official wandb and hydra pages.

**Comment by cool-RR** [comment]
Sorry that I'm so critical about these things. It's because I'm coming from the software engineering and open-source worlds to the research world. I often complain about such things, and even though I know that research code has a lower bar of user-friendliness than a regular open-source Python package, I always have to fight myself to not open too many bugs / point out usability problems.

Such a tutorial would be helpful, yes. In the meanwhile I'll be trying to figure out Pax on my own.
