### ISSUE TITLE
Question about `num_opps`

### ISSUE THREAD

**Issue by alexunderch** [ucl-dark/pax#175]
What does `num_opps` stand for  and how it is used in runners? Because I see this variable a lot in configs and algorithms and couldn't understand what one is for.

**Comment by akbir** [comment]
it's the number of concurrent co-players (of different weight initialisations) the shaper plays against

**Comment by alexunderch** [comment]
Thus, if a game has `n` players, on each iteration the modelled agent plays against `n-1` opponents — and this number is called `num_opps`. Did I understand correctly?

**Comment by Aidandos** [comment]
Let's say you play the Iterated Prisoner's Dilemma (IPD), which is a 2-player game. `num_opps` defines against how many opponents you play the in parallel. For example, `num_opps=10` means you play the IPD against 10 opponents in parallel. In this case, it is similar to `num_envs` as opponent initialization and environment initialization are the same thing.

Total batch_size would be `num_envs` * `num_opps`.

`num_envs` and `num_opps` are especially useful in the more expressive, meltingpot-like environments. You can imagine that you'd want your batch to contain multiple envs and multiple opponent initializations at each time step to get a good training signal. Let me know if that clarifies things!

**Comment by Aidandos** [comment]
To play the multi-player IPD, you have to set `num_players` to how many opponents you want to play against. Apologies for the confusing naming.

See this [config](https://github.com/ucl-dark/pax/blob/main/pax/conf/experiment/multiplayer_ipd/3pl_2shap_ipd.yaml) as an example.

**Comment by alexunderch** [comment]
Oh, I got it, the opponent refers not to player itself but to its initialisation, for example, it doesn't contradict with a player playing against itself. Thank you for the examples. If I don't have more questions, I will close the issue shortly
